name: kamariati_cosmetic_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  fluentui_system_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  readmore: ^3.0.0
  rename: ^3.0.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/kamariati_cosmetic_icon.png"

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
